var App={idTimeoutResize:0,deviceType:null,widthWindow:null,orientationDevice:null,namePage:null,launch:function(){var namePage=$('body div[data-page]').attr('data-page');nameClass=namePage.charAt(0).toUpperCase();nameClass=nameClass+namePage.substr(1);App.namePage=namePage;App.eventGoTo();App.eventOrientation();App.eventMenu();App.eventCookiePolicy();App.eventBackTop();App.eventResize();if(typeof window[nameClass]!='undefined'&&typeof window[nameClass]['launch']!='undefined'){window[nameClass]['launch']();console.info('Load class Â« '+nameClass+' Â» with method launch');}},eventResize:function(){App.actionResize();$(window).on('resize',function(){clearTimeout(App.idTimeoutResize);App.idTimeoutResize=setTimeout(App.actionResize,500);});},eventOrientation:function(){$(window).on('orientationchange',function(){if(Math.abs(window.orientation)===90)
App.orientationDevice='paysage';else
App.orientationDevice='portrait';});},eventGoTo:function(){var hash=window.location.hash;var regex=new RegExp('^#top=([0-9]+)','i');if(regex.test(hash)){var matches=regex.exec(hash);var top=parseInt(matches[1]);$('body, html').scrollTop(top);history.replaceState({},document.title,window.location.pathname);}
$('body a[href^="#"]').on('click',function(event){App.actionGoTo($(this).attr('href'),$(this));event.preventDefault();return false;});},eventBackTop:function(){$(window).on('resize scroll',function(){var $elBack=$('body > div[name="backTop"]');if($(window).width()>800&&$(this).scrollTop()>250)
$elBack.fadeIn();else
$elBack.fadeOut();});},eventCookiePolicy:function(){var $el=$('body div[name="cookiePolicy"]');if($.cookie('cookiePolicy')!=='accepted'){$el.removeClass('no-display').addClass('display');console.info('First visit : display cookie policy');}
$el.on('click',function(){App.closeCookiePolicy($(this));});$el.find('a').on('click',function(){App.closeCookiePolicy($(this).parents('div'));});},eventMenu:function(){var $el=$('body a[name="menuSmallScreen"]');$el.on('click',function(event){if(App.deviceType=='mobile'){$(this).parents('nav').toggleClass('show');event.preventDefault();return false;}});},actionGoTo:function(hashEl,$elStart){var $elCible=$(hashEl);var $elNav=$('body > nav');if($elCible.length>0){var heightNav=0;var duration='normal';if($elNav.length>0&&$elNav.css('position')=='fixed')
heightNav=parseInt($elNav.outerHeight());if(typeof $elStart.attr('data-duration')!='undefined')
duration=$elStart.attr('data-duration');console.info('goTo Â« '+hashEl+' Â» width duration Â« '+duration+'Â»');switch(duration){case'speed':duration='250';break;case'slow':duration='750';break;case'medium':default:duration='500';break;}
var positionTop=parseInt($elCible.position().top)-heightNav;$('body, html').animate({scrollTop:positionTop},duration,'swing',function(){history.replaceState({},document.title,hashEl);});}},actionResize:function(){App.widthWindow=parseInt($(window).width());if(App.widthWindow<=640)
App.deviceType='mobile';else if(App.widthWindow<=800)
App.deviceType='tablet';else
App.deviceType='desktop';console.info('Params display : widthWindow = '+App.widthWindow+', deviceType = '+App.deviceType);},closeCookiePolicy:function($el){$el.removeClass('display').addClass('no-display');$.cookie('cookiePolicy','accepted',{expires:93});}};$(document).ready(function(){App.launch();});var Home={launch:function(){}};var Presentation={launch:function(){$('div[name="listPicture"] a.fancybox').each(function(){$(this).attr('data-fancybox-group','gallery');});$('div[name="listPicture"] a.fancybox').fancybox({'afterLoad':Presentation.addLinks,'beforeClose':Presentation.removeLinks});},addLinks:function(){var list=$("#fancybox-links");if(!list.length){list=$('<ul id="fancybox-links">');for(var i=0;i<this.group.length;i++){$('<li data-index="'+i+'"><label></label></li>').click(function(){$.fancybox.jumpto($(this).data('index'));}).appendTo(list);}
list.appendTo('body');}
list.find('li').removeClass('active').eq(this.index).addClass('active');},removeLinks:function(){$("#fancybox-links").remove();}};var Registration={idTimeoutForm:0,saveValueFields:{},launch:function(){Registration.eventListRadio();Registration.eventFieldForm();},eventListRadio:function(){$('div.listRadio').on('mouseenter mouseleave',function(event){$(this).find('a').each(function(){if(event.type=='mouseenter')
$(this).attr('data-activate',$(this).hasClass('activate')?'true':'false');else if(event.type=='mouseleave'){if($(this).attr('data-activate')=='true')
$(this).addClass('activate');}});if(event.type=='mouseenter')
$(this).find('a').removeClass('activate');else if(event.type=='mouseleave')
$(this).find('a').removeAttr('data-activate');});$('a[data-top="true"]').on('click',function(){if(!/#/.test($(this).attr('href')))
$(this).attr('href',$(this).attr('href')+'#top='+$(window).scrollTop());})},eventFieldForm:function(){$('div[name="formCreate"] form input').on('keyup change',function(){if(Registration.fieldsFormModified()){Registration.saveValueFields=Registration.getFieldsForm();clearTimeout(Registration.idTimeoutForm);Registration.idTimeoutForm=setTimeout(Registration.previewForm,400);}});},fieldsFormModified:function(){var fields=Registration.getFieldsForm();var refresh=false;$.each(fields,function(nameField,value){if(typeof Registration.saveValueFields[nameField]=='undefined')
refresh=true;else if(Registration.saveValueFields[nameField]!=value)
refresh=true;});return refresh;},previewForm:function(){var $elForm=$('div[name="formCreate"] form');var idUnivers=$elForm.find('input[name="idUnivers"]').val();$.post('verifyDB.php?&id='+idUnivers,Registration.getFieldsForm(),function(json){$.each(json,function(nameField,datas){var $elInput=$elForm.find('input[name="'+nameField+'"]');var $elInfo=$elInput.parents('div.champ').next('div');$elInfo.removeClass('color-green color-grey color-red');$elInfo.addClass('color-'+datas.color).text(datas.message+'.');});},'json');},getFieldsForm:function(){var fields={};$('div[name="formCreate"] form input').each(function(){var nameField=$(this).attr('name');if(typeof nameField!='undefined')
fields[nameField]=$(this).val();});return fields;}};var Rule={launch:function(){Rule.eventGoTo();Rule.eventHashUrl();},eventGoTo:function(){$('div[data-page] a[href^="#"]').on('click',function(event){Rule.actionGoTo($(this).attr('href'));event.preventDefault();return false;});},eventHashUrl:function(){var hashEl=window.location.hash;App.actionGoTo(hashEl);Rule.actionGoTo(hashEl);},actionGoTo:function(hashEl){var $elCible=$(hashEl);var $elPage=$elCible.parents('div[data-page]');if($elCible.length>0){$elPage.find('article.activate').removeClass('activate');$elCible.next('article').addClass('activate');}}};function setLNG(o,e){var n="lang";document.cookie=n+"="+o,"undefined"==typeof e?document.location.reload():document.location.href=document.location.href+e}